# Generated by Django 5.2.9 on 2026-07-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField(unique=True)),
                ('generated_at_local', models.CharField(max_length=40)),
                ('source_mode', models.CharField(max_length=64)),
                ('forecast_tmin24_c', models.FloatField(null=True)),
                ('forecast_tmean72_c', models.FloatField(null=True)),
                ('forecast_tmax24_c', models.FloatField(null=True)),
                ('target_interval_days', models.FloatField(null=True)),
                ('interval_demand_mm', models.FloatField(null=True)),
                ('forecast_precip_local_day_mm', models.FloatField(null=True)),
                ('forecast_precip_next24_mm', models.FloatField(null=True)),
                ('effective_rain_today_mm', models.FloatField(null=True)),
                ('recent_rain_mm', models.FloatField(null=True)),
                ('rain_postpone_threshold_mm', models.FloatField(null=True)),
                ('rain_reset_threshold_mm', models.FloatField(null=True)),
                ('decision_code', models.CharField(max_length=32)),
                ('decision_label', models.CharField(max_length=32)),
                ('should_irrigate_now', models.BooleanField(default=False)),
                ('commanded_percent', models.IntegerField(default=0)),
                ('commanded_pump_seconds', models.IntegerField(default=0)),
                ('event_completed', models.BooleanField(default=False)),
                ('event_epoch', models.BigIntegerField(null=True)),
                ('event_solar_anchor', models.CharField(blank=True, max_length=16)),
                ('last_event_epoch', models.BigIntegerField(null=True)),
                ('next_watering_epoch', models.BigIntegerField()),
                ('next_watering_iso_local', models.CharField(max_length=40)),
                ('projected_following_epoch', models.BigIntegerField()),
                ('projected_following_iso_local', models.CharField(max_length=40)),
                ('schedule_armed', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['local_date'],
            },
        ),
        migrations.CreateModel(
            name='MetarReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at_epoch', models.BigIntegerField()),
                ('logged_at_local', models.CharField(max_length=40)),
                ('obs_time_epoch', models.FloatField(null=True)),
                ('obs_time_local', models.CharField(blank=True, max_length=40)),
                ('age_minutes', models.FloatField(null=True)),
                ('station', models.CharField(blank=True, max_length=8)),
                ('station_name', models.CharField(blank=True, max_length=128)),
                ('temp_c', models.FloatField(null=True)),
                ('dewpoint_c', models.FloatField(null=True)),
                ('rh_pct', models.FloatField(null=True)),
                ('wind_mps', models.FloatField(null=True)),
                ('wind_dir_deg', models.CharField(blank=True, max_length=16, null=True)),
                ('pressure_hpa', models.FloatField(null=True)),
                ('vpd_kpa', models.FloatField(null=True)),
                ('raw_ob', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['obs_time_epoch'],
                'indexes': [models.Index(fields=['obs_time_epoch'], name='dashboard_m_obs_tim_ff0370_idx')],
            },
        ),
    ]
