# Generated by Django 5.2.9 on 2026-07-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationdecision',
            name='station',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
